### PR TITLE
Extents VLR draft

### PR DESCRIPTION
**Pull request by hobu**
As discussed in #19.

### CODE REVIEW

**Comment by CCInc** [comment]
So did we scrap mean/median/variance then? I think those would future-proof the format and add very little overhead to the file

**Comment by hobu** [comment]
> So did we scrap mean/median/variance then? I think those would future-proof the format and add very little overhead to the file

Much 🧇'ing.

**Comment by connormanning** [comment]
To me, the mean/variance fields are a half-measure - aside from the extents which are quite useful, what you really probably want is bucketed counts, potentially histograms at various or adaptive bin sizes, maybe other stats, etc.  I think the `mean` and `variance` are not useful enough to require as part of the core spec and just add complication for writers (I just included them here because EPT had them), and rather that some optional VLR targeting rendering statistics could be specified in the future to capture these more sophisticated scenarios.

**Comment by hobu** [comment]
It's a tough balancing act, and this is why we've been 🧇'ing so much. First is how to provide enough simple metadata to a renderer to make some sliders for dimension rendering. We know from Potree and Plasio this is a very strong need. The second is to keep the writers as simple as possible so they don't have to do extra work to produce data that no one will use. 

`mean` isn't that expensive to compute, but `variance` is a little bit expensive and can be challenging to do in a way that doesn't require all of the data at once. What could a client do with `mean`? I suppose they could easily adjust the rendering of a grouping of COPC files to normalize them in some way, but doing that probably requires a much more resolute histogram than mean/stddev provide. A renderer can't do much with `variance` without making assumptions about the shape of the histogram. In that case, I think you'd much rather have the histogram.

After hashing it out, we don't want to require a complicated VLR that only exists to support certain kinds of rendering tricks. If the COPC rendering community (if there ever is one) wants to come up with an optional EVLR that can be placed at the end of the file, I think that would serve the need in an unobtrusive way – people who wanted to "render optimize" their COPC files could write a bit of software to cumulate these stats and stick them on the end as a VLR. Then it could include fancy histograms, transformations, and many of the other things Markus might want to make pretty pictures. 

The capability to provide dimension ranges that the currently proposed VLR provides is a simple extension of something that was missing in LAS. What can you do with just the ranges as we've proposed here?

* Know if a field is actually populated with data (min != max)
* Know if the `Intensity` field is using 8-bit or 16-bit range
* Guestimate `GPSTime` situation based on range
* Know if the data have any flagged points

We think this is enough, but we would like to hear concrete reasons why it isn't if you have them.

**Review by connormanning — APPROVED** [review]

**Comment by CCInc** [comment]
So we can do:

```
struct CopcInfo
{
  int64_t span;                 // Number of voxels in each spatial dimension (typically powers of 2)
  uint64_t root_hier_offset;    // File offset to the first hierarchy page
  uint64_t root_hier_size;      // Size of the first hierarchy page in bytes
  uint64_t laz_vlr_offset;      // File offset of the *data* of the LAZ VLR
  uint64_t laz_vlr_size;        // Size of the *data* of the LAZ VLR.
  uint64_t wkt_vlr_offset;      // File offset of the *data* of the WKT VLR if it exists, 0 otherwise
  uint64_t wkt_vlr_size;        // Size of the *data* of the WKT VLR if it exists, 0 otherwise
  uint64_t eb_vlr_offset;       // File offset of the *data* of the extra bytes VLR if it exists, 0 otherwise
  uint64_t eb_vlr_size;         // Size of the *data* of the extra bytes VLR if it exists, 0 otherwise
  uint64_t extent_vlr_offset;
  uint64_t extent_vlr_size;
  uint64_t reserved[9];        // Reserved for future use. Must be 0.
};
```
?

What else do we need to get it across the line?

**Comment by hobu** [comment]
> What else do we need to get it across the line?

definition of the cube with a centerpoint and a distance needs to go in the `info` VLR as well.

**Comment by timodwhit** [comment]
@hobu What do you mean by "a distance"?

**Comment by timodwhit** [comment]
@hobu Sorry, reflecting on this: 

- What cube?
- What centerpoint? The centerpoint of the cube?
- What does "a distance" refer to?

Is there previous discussion of these in the issue queue? we aren't seeing them

**Comment by abellgithub** [comment]
See: https://github.com/copcio/copcio.github.io/issues/26#issuecomment-920318010

**Comment by abellgithub** [comment]
We should remove the extra bytes dims from this VLR as they're already in the EB VLR.

**Comment by hobu** [comment]
> We should remove the extra bytes dims from this VLR as they're already in the EB VLR.

So if we were to fully normalize as suggested:
* XYZ ranges from the header
* ReturnNumber ranges from the header (current language doesn't do that)
* PointSourceId-defined dimensions from this `extents` VLR
* EB VLR ranges from EB VLR item headers

If we were to provide everything in the extents VLR:
*  Add range entries in order for all dimensions including XYZ, but not including bitfields.

At risk of the extents VLR data being out of sync with those other places, let's go with the latter. Not as much hopping around, not as much dimension checking logic when writing or reading it, and maybe it is an example going forward for LAS if there ever is another LAS version.

**Comment by leo-stan** [comment]
@abellgithub @hobu do you plan on adding a new VLR for extents in lazperf to go along lazperf::copc_vlr? Or just adding the offset and size in the current copc_vlr?

**Comment by hobu** [comment]
> do you plan on adding a new VLR for extents in lazperf to go along 

It is included in https://github.com/hobu/laz-perf/pull/102 but I was waiting on the dust to settle on the `info` VLR before merging. We will make a new laz-perf release when we are ready to go final with COPC 1.0

**Comment by leo-stan** [comment]
Ah great, thanks!

**Pull request merged**
